events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name api.beatvault.ru;
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name api.beatvault.ru;

        ssl_certificate /etc/nginx/ssl/live/beatvault.ru/fullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/live/beatvault.ru/privkey.pem;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}
